### ISSUE TITLE
bandolier vs closure compiler

### ISSUE THREAD

**Issue by caridy** [shapesecurity/bandolier#11]
Latest version of closure compiler can aggregate files very similarly, I wonder if there is any considerable differences considering that closure compiler is somewhat slow and very convoluted to set up correctly.

**Comment by disnet** [comment]
Oh cool, I didn't know closure had added ES2015 module support.

As far as differences go, the closure compiler does a bunch of checking and optimization passes which bandolier does not even attempt to do. From some quick poking around in their docs it's unclear if module resolving/loading is pluggable like in bandolier.

**Comment by michaelficarra** [comment]
Closing as answered.
