### ISSUE TITLE
publish as a npm package

### ISSUE THREAD

**Issue by disnet** [shapesecurity/bandolier#12]

**Comment by michaelficarra** [comment]
![what does that even mean?](http://i.giphy.com/l2JdYQ26BM6uFxPsA.gif)

**Comment by LewisJEllis** [comment]
It means make something like rollup, except it's just a thin wrapper around bandolier. So then I can have `bandolier` in my devDependencies and then have an npm script do `bandolier blah.js --out blah.bundled.js` and do what I want, without having to carry around the bandolier jar/shell script in all my projects. We can publish it openly to npm, and then people can use bandolier just like they use rollup.

**Comment by michaelficarra** [comment]
Okay. They're going to have to have a JVM around for it to work. Meh.

**Comment by LewisJEllis** [comment]
Fine by me, I just want to be able to put bandolier in my devDependencies and be on my way.

**Comment by michaelficarra** [comment]
Why not just put rollup in your devDependencies instead?

**Comment by LewisJEllis** [comment]
My specific reason to not just use rollup, while making so many comparisons to it, is that bandolier does exactly what I want in all cases out of the box, and is the same thing we use elsewhere. Rollup does exactly what I want in lots of cases, but sometimes requires additional configuration/plugins, and it isn't the exact same thing we use everywhere.
